# Form implementation generated from reading ui file 'add_user.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(380, 379)
        self.add_btn = QtWidgets.QPushButton(parent=Form)
        self.add_btn.setGeometry(QtCore.QRect(100, 340, 201, 28))
        self.add_btn.setObjectName("add_btn")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(50, 30, 301, 261))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.login_lineEdit.setObjectName("login_lineEdit")
        self.verticalLayout.addWidget(self.login_lineEdit)
        self.passw_lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.passw_lineEdit.setObjectName("passw_lineEdit")
        self.verticalLayout.addWidget(self.passw_lineEdit)
        self.fio_lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.fio_lineEdit.setObjectName("fio_lineEdit")
        self.verticalLayout.addWidget(self.fio_lineEdit)
        self.email_lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.verticalLayout.addWidget(self.email_lineEdit)
        self.widget1 = QtWidgets.QWidget(parent=Form)
        self.widget1.setGeometry(QtCore.QRect(110, 300, 211, 21))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.manager_rb = QtWidgets.QRadioButton(parent=self.widget1)
        self.manager_rb.setObjectName("manager_rb")
        self.horizontalLayout.addWidget(self.manager_rb)
        self.user_rb = QtWidgets.QRadioButton(parent=self.widget1)
        self.user_rb.setObjectName("user_rb")
        self.horizontalLayout.addWidget(self.user_rb)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.add_btn.setText(_translate("Form", "Добавить пользователя"))
        self.login_lineEdit.setPlaceholderText(_translate("Form", "Введите логин"))
        self.passw_lineEdit.setPlaceholderText(_translate("Form", "Введите пароль"))
        self.fio_lineEdit.setPlaceholderText(_translate("Form", "Введите ФИО"))
        self.email_lineEdit.setPlaceholderText(_translate("Form", "Введите email"))
        self.manager_rb.setText(_translate("Form", "Manager"))
        self.user_rb.setText(_translate("Form", "User"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
