# Form implementation generated from reading ui file 'user_window.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UserWindow(object):
    def setupUi(self, UserWindow):
        UserWindow.setObjectName("UserWindow")
        UserWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(parent=UserWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.contractsTab = QtWidgets.QWidget()
        self.contractsTab.setObjectName("contractsTab")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.contractsTab)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.contractsTable = QtWidgets.QTableWidget(parent=self.contractsTab)
        self.contractsTable.setObjectName("contractsTable")
        self.contractsTable.setColumnCount(0)
        self.contractsTable.setRowCount(0)
        self.verticalLayout_1.addWidget(self.contractsTable)
        self.addContractBtn = QtWidgets.QPushButton(parent=self.contractsTab)
        self.addContractBtn.setObjectName("addContractBtn")
        self.verticalLayout_1.addWidget(self.addContractBtn)
        self.tabWidget.addTab(self.contractsTab, "")
        self.tasksTab = QtWidgets.QWidget()
        self.tasksTab.setObjectName("tasksTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tasksTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tasksTable = QtWidgets.QTableWidget(parent=self.tasksTab)
        self.tasksTable.setObjectName("tasksTable")
        self.tasksTable.setColumnCount(0)
        self.tasksTable.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tasksTable)
        self.addTaskBtn = QtWidgets.QPushButton(parent=self.tasksTab)
        self.addTaskBtn.setObjectName("addTaskBtn")
        self.verticalLayout_2.addWidget(self.addTaskBtn)
        self.tabWidget.addTab(self.tasksTab, "")
        self.archiveTab = QtWidgets.QWidget()
        self.archiveTab.setObjectName("archiveTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.archiveTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.searchInput = QtWidgets.QLineEdit(parent=self.archiveTab)
        self.searchInput.setObjectName("searchInput")
        self.verticalLayout_3.addWidget(self.searchInput)
        self.archiveTable = QtWidgets.QTableWidget(parent=self.archiveTab)
        self.archiveTable.setObjectName("archiveTable")
        self.archiveTable.setColumnCount(0)
        self.archiveTable.setRowCount(0)
        self.verticalLayout_3.addWidget(self.archiveTable)
        self.tabWidget.addTab(self.archiveTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        UserWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UserWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UserWindow)

    def retranslateUi(self, UserWindow):
        _translate = QtCore.QCoreApplication.translate
        UserWindow.setWindowTitle(_translate("UserWindow", "Панель пользователя"))
        self.addContractBtn.setText(_translate("UserWindow", "Добавить договор"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.contractsTab), _translate("UserWindow", "Договоры"))
        self.addTaskBtn.setText(_translate("UserWindow", "Добавить поручение"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tasksTab), _translate("UserWindow", "Поручения"))
        self.searchInput.setPlaceholderText(_translate("UserWindow", "Поиск по архиву"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.archiveTab), _translate("UserWindow", "Архив"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserWindow = QtWidgets.QMainWindow()
    ui = Ui_UserWindow()
    ui.setupUi(UserWindow)
    UserWindow.show()
    sys.exit(app.exec())
